/** Retired factory catalog IDs — never seed or restore these from leftover backups. */
export const RETIRED_FACTORY_SERVICE_IDS = [
  "netflix-private",
  "netflix-prime",
  "youtube-premium",
  "iptv",
  "canva",
  "nordvpn",
  "grok",
  "google-gemini",
  "capcut-pro",
  "mubi",
  "hulu",
  "peacock",
  "sonyliv",
  "starzplay",
  "osn-plus",
  "disney-plus",
  "shahid",
  "chatgpt-plus",
  "crunchyroll",
  "paramount-plus",
  "hbo-max",
  "zee5",
  "apple-tv-plus",
  "apple-music",
  "youtube-music",
  "spotify-premium",
  "proton-vpn",
  "cyberghost-vpn",
  "surfshark-vpn",
  "expressvpn",
];

/** No baked-in catalog. Admin adds services after publish. */
export const DEFAULT_SERVICES = [];
